### ISSUE TITLE
Create, Modify, Retrieve User Data Endpoints

### ISSUE THREAD

**Issue by winstonbullen** [winstonbullen/DuoCode#15]

**Comment by jgao222** [comment]
Winston mentioned this might be related to #28 but I think an important aspect of user data which is still missing is persistent storage of user progress. Adding this might require a new endpoint to modify and retrieve this part of the user data, and changes to the UserInfoDB interface to add methods for storing progress information.

I am open to suggestions if anyone has ideas on how to store user info. I was just thinking to simply have a big list of all the names of completed exercises but I'm not sure if that will work well.

**Comment by winstonbullen** [comment]
I think that solution would work fine. This is the reference we wrote in the living doc. Probably one GET endpoint to retrieve the user data. One POST endpoint to add a completed milestone. 
![image](https://user-images.githubusercontent.com/52332581/236719738-879cdb0c-192b-4330-90f3-eaad1099b1ef.png)
